from dataclasses import dataclass

@dataclass(frozen=True)
class EgressError(Exception):
    code: str
    message: str
    retryable: bool = False
    def __str__(self) -> str:
        return f"{self.code}: {self.message}"

MALFORMED = "EF-001"
NO_AUTHORITY = "EF-002"
INVALID_AUTHORITY = "EF-003"
STALE_AUTHORITY = "EF-004"
ALREADY_USED = "EF-005"
REPLAY = "EF-006"
NONCE_FAILURE = "EF-007"
ACT_MISMATCH = "EF-010"
DESCRIPTOR_MISMATCH = "EF-011"
SCOPE_MISMATCH = "EF-012"
DESTINATION_MISMATCH = "EF-020"
JURISDICTION_MISMATCH = "EF-021"
PRECISION_MISMATCH = "EF-023"
POLICY_EPOCH_MISMATCH = "EF-030"
REVOCATION_MISMATCH = "EF-031"
PROTECTED_STATE_MISMATCH = "EF-032"
SINK_MISMATCH = "EF-040"
VALIDATION_TIMEOUT = "EF-060"
AUTHORITY_UNCERTAIN = "EF-061"
POLICY_UNAVAILABLE = "EF-062"
JURISDICTION_UNRESOLVED = "EF-063"
ESCALATION_REQUIRED = "EF-070"
FAIL_CLOSED = "EF-080"
PAYLOAD_UNINSPECTABLE = "EF-081"
FIELD_SCOPE_MISMATCH = "EF-082"
RETENTION_MISMATCH = "EF-083"
EVIDENCE_MISSING = "EF-084"
ACTIVATION_MISSING = "EF-085"
